import { useEffect } from 'react'

const ARG_JUMP_LINK_SELECTOR = 'a.token.arg[href^="#"]'
const ARG_TARGET_FLASH_CLASS = 'arg-target-flash'
const ARG_TARGET_FLASH_DURATION = 1000

// This hook uses DOM events directly because synopsis links and option targets
// are generated by Prism/remark, not owned as React elements in this component.
export const useArgsTargetFlash = (): void => {
  useEffect(() => {
    if (!document.querySelector(ARG_JUMP_LINK_SELECTOR)) return

    let frameId: number | null = null
    let timeoutId: number | null = null

    const flashRow = (id: string) => {
      const target = document.getElementById(id)
      const row = target?.closest('li')
      if (!row) return

      if (frameId) {
        window.cancelAnimationFrame(frameId)
      }
      if (timeoutId) {
        window.clearTimeout(timeoutId)
      }

      row.classList.remove(ARG_TARGET_FLASH_CLASS)
      frameId = window.requestAnimationFrame(() => {
        row.classList.add(ARG_TARGET_FLASH_CLASS)
        timeoutId = window.setTimeout(() => {
          row.classList.remove(ARG_TARGET_FLASH_CLASS)
        }, ARG_TARGET_FLASH_DURATION)
      })
    }

    const handleOptionClick = (event: MouseEvent) => {
      const link = (event.target as HTMLElement).closest?.(
        ARG_JUMP_LINK_SELECTOR
      ) as HTMLAnchorElement | null
      if (!link) return

      const id = decodeURIComponent(link.getAttribute('href')?.slice(1) || '')
      if (!id) return

      window.setTimeout(() => flashRow(id), 0)
    }

    document.addEventListener('click', handleOptionClick, true)

    return () => {
      if (frameId) {
        window.cancelAnimationFrame(frameId)
      }
      if (timeoutId) {
        window.clearTimeout(timeoutId)
      }
      document.removeEventListener('click', handleOptionClick, true)
    }
  }, [])
}
